parameters:
#    my_command.example.class: SebaThomson\MyCommandBundle\Example

services:
#    my_command.example:
#        class: %my_command.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
